Tick/Tick/urls.py
from django.contrib import admin
from django.urls import path, include



from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('',include('accounts.urls')),
] 

urlpatterns += static(settings.MEDIA_URL,
                              document_root=settings.MEDIA_ROOT)

Tick/accounts/urls.py
from django.urls import path, include
from . import views

app_name='accounts'

urlpatterns = [
    path('register',views.Register, name='signUp'),
    path('login', views.signin, name="login"),
    path("logout",views.user_logout, name="logout"),
]

Tick/main/urls.py
from django.urls import path, include
from main.views import PostView,PostDetail,AddPost,UpdatePost,DeletePost,ProfileView, CommentPost

app_name='main'



urlpatterns = [
    path('',PostView.as_view(), name='home'),
    path('create_post/', AddPost.as_view(), name="create" ),
    path('details/<int:pk>', PostDetail.as_view(), name="details"),
    path('detail/update/<int:pk>',UpdatePost.as_view(), name="update"),
    path('detail/<int:pk>/Delete',DeletePost.as_view(), name="Delete"),
    path('profile/',ProfileView, name='profile'),
    path('details/<int:pk>/comment', CommentPost.as_view(), name="add_comment"),
]

Tick/main/models.py
from distutils.command.upload import upload
from email.mime import image
from typing_extensions import Required
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from ckeditor.fields import RichTextField
from pkg_resources import require


class BlogPost(models.Model):
    Author = models.ForeignKey(User, on_delete=models.CASCADE,)
    Title = models.CharField(max_length=255)
    Images =models.ImageField(blank=True,null=True, upload_to="images/user_upload")
    Date_Created=models.DateTimeField(auto_now=True)
    Body= RichTextField(blank=True, null=True)
    def __str__(self):
        return (self.Title+" " +"|By:"+" " +str(self.Author))
    
    def get_absolute_url(self):
        return reverse('main:home', args=(str(self.pk)))

class Profile(models.Model):
    user=models.OneToOneField(User, related_name='picture',
                              on_delete=models.CASCADE)
    Profile_pic =models.ImageField(blank=True,null=True, upload_to="images/profile_pic")
    def __str__(self):
        return str(self.user)

class Comment_post(models.Model):
    post = models.ForeignKey(BlogPost, related_name ='comment',on_delete=models.CASCADE,)
    name=models.CharField(max_length=255)
    body=  models.TextField()
    date_added= models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return '%s - %s' %(self.post.Title, self.name)

Tick/main/forms.py
from logging import PlaceHolder
from tkinter import Widget
from django import forms
from .models import Profile,BlogPost,Comment_post


class PostForm(forms.ModelForm):
    Title=forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    #Author=forms.CharField(widget=forms.Select(attrs={'class': 'form-control', 'id':'author'}))
    Author=forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'id':'author','placeholder':'username'}))
    #Images=forms.ImageField(, required=False)(attrs={'class': 'form-control'}))
    Body=forms.CharField(widget=forms.Textarea(attrs={'class': 'form-control'})) 
     
    class Meta:
        model=BlogPost
        fields=("Title","Author","Images","Body")
        
    # def __init__(self, *args, **kwargs):
    #     super(PostForm, self).__init__(*args, **kwargs)
    #     [
    #     self.fields['Title'].widget.attrs.update({'class': 'form-control'}),
    #     self.fields['Author'].widget.attrs.update({'class': 'form-control','id':'author'}),
    #     self.fields['Body'].widget.attrs.update({'class': 'form-control'}),
        
    #     ]
        # widgets = {
        #     'Title':forms.TextInput(attrs ={'class':'form-control'}),
        #     'Author':forms.ChoiceField(attrs={'class':'form-control'}),
        #     'Body':forms.Textarea(attrs={'class':'form-control'}),
        # }

class ProfileForm(forms.ModelForm):
    User=forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'id':'author','placeholder':'username'}))
    class Meta:
        model = Profile
        fields= ('User','Profile_pic') 
        
class CommentForm(forms.ModelForm): 
    name=forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    #Author=forms.CharField(widget=forms.Select(attrs={'class': 'form-control', 'id':'author'}))
    body=forms.CharField(widget=forms.Textarea(attrs={'class': 'form-control'}))
    class Meta:
        model=Comment_post
        fields=("name","body")
        #fields='__all__'
        
    # def __init__(self, *args, **kwargs):
    #     super(PostForm, self).__init__(*args, **kwargs)
    #     [
    #     self.fields['Title'].widget.attrs.update({'class': 'form-control'}),
    #     self.fields['Author'].widget.attrs.update({'class': 'form-control','id':'author'}),
    #     self.fields['Body'].widget.attrs.update({'class': 'form-control'}),
        
    #     ]
        # widgets = {
        #     'Title':forms.TextInput(attrs ={'class':'form-control'}),
        #     'Author':forms.ChoiceField(attrs={'class':'form-control'}),
        #     'Body':forms.Textarea(attrs={'class':'form-control'}),
        # } 

Tick/main/views.py
from django.shortcuts import render,redirect
from django.urls import reverse_lazy
from .models import BlogPost,Profile,Comment_post
from django.http import HttpResponseRedirect
from django.views.generic import ListView, DetailView, CreateView,UpdateView,DeleteView
from .forms import ProfileForm, PostForm,CommentForm



def ProfileView(request):
    if request.method == 'POST':
        form = ProfileForm(request.POST, request.FILES)
        
        if form.is_valid():
            form.save()
            return HttpResponseRedirect("/") 
    else:
        form = ProfileForm

    return render(request, 'profile.html', {'form':form})


class PostView(ListView):
    model= BlogPost
    form_class= PostForm
    prof=Profile.objects.filter()
    template_name='index.html'
    ordering=["-id"]
    
class PostDetail(DetailView):
    model=BlogPost
    template_name='detail.html'
    
class AddPost(CreateView):
    model=BlogPost
    form_class=PostForm
    template_name='add_post.html'
    #fields="__all__"
    success_url= reverse_lazy('main:home')
    
class UpdatePost(UpdateView):
    model=BlogPost
    template_name= 'updates.html'
    fields=('Title','Body')
    success_url= reverse_lazy('main:home')
    
class DeletePost(DeleteView):
    model=BlogPost
    template_name='delete.html'
    success_url= reverse_lazy('main:home')

class CommentPost(CreateView):
    model=Comment_post
    form_class=CommentForm
    template_name='add_comment.html'
    #fields="__all__"
    
    def form_valid(self,form):
        form.instance.post_id = self.kwargs['pk']
        return super().form_valid(form)
    
    success_url= reverse_lazy('main:home')

Tick/main/templates/add_comment.html
{% extends 'global.html' %}

{% block content %}

        <form  class="form-control" method="Post">
            <h1 align="center">Make comment</h1>
            {% csrf_token %}
            {{form.as_p}}
            <button class="btn btn-primary">Post</button> 
            
            {% comment %} <script> 
                var name="{{user.pk}}";
                document.getElementById("author").placeholder
                    =name;
               </script> {% endcomment %}
{% endblock %}












    
    

Tick/main/templates/add_post.html
{% extends 'global.html' %}

{% block content %}

    {% if user.is_authenticated %}
        <form  class="form-control" method="Post">
            <h1 align="center">Create New Post</h1>
            {% csrf_token %}
            {{form.as_p}}
            {{form.media}}
            <button class="btn btn-primary">Post</button>    
       <script> 
        var name="{{user.username}}";
        document.getElementById("author").placeholder
            =name;
       </script>
       {% else %}
       <h3> you are not allowed to make a post unless you logged In </h3>

       {% endif %}
{% endblock %}












    
    

Tick/main/templates/delete.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link rel="shortcut icon" href="./Images/favicon.ico" type="image/x-icon" />
        <link
            href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;700&family=Jost:wght@500;700&family=Oxanium:wght@400;500;600;700&display=swap"
            rel="stylesheet"
            />
            <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
        <link rel="stylesheet" href="{% static 'css/style.css' %}" />
        <script src="{% static 'javascripts/script.js' %}" defer></script>
        <title>Tick-Blog</title>
    </head>
    <body>
        <header>
            <!-- desktop menu -->
            <div class="desktop_menu">
                <div class="desktop_menu-rside">
                    <div>
                        <a href="{% url 'main:home' %}" class="logo_heading">Tick</a>
                    </div>
                    <div class="search_box">
                        <input type="search" placeholder="Search.." />
                        <button class="search-btn"></button>
                    </div>
                </div>
                <nav class="desktop_nav">
                    <img class="dark" onclick="setTheme('dark')" style="width: 5.3%;" src="{% static 'Images/toggle.svg' %}"
                        alt="dark mode icon">
                    <img onclick="setTheme('light')" class="light" style="width: 5.3%;" src="{% static 'Images/toggle.svg' %}"
                        alt="light mode icon">
        
                        {% if user.is_authenticated %}
                            
                        <ul>
                            <li>
                              <a href="#">welcome, {{user.username}}</a>
                            </li>
                            <li>
                                <a href="{% url 'main:create' %}">Add Post</a>
                              </li>
                              
                            <li>
                                <a href="{% url 'main:profile' %}">Add profile Picture </a>
                              </li>
                            <li><a href="{% url 'accounts:logout' %}">Logout</a></li>
                            </ul>
                            
                            {% else %}
                            
                            <li><a href="{% url 'accounts:login' %}" class="create_acct_btn">Login</a></li>
                            <li><a href="{% url 'accounts:signUp' %}" class="create_acct_btn">Create account</a></li> 
                            </ul>
                        {% endif %}

                </nav>
            </div>
            <!-- mobile menu -->
            <div class="mobile_menu">
                <div>
                    <a href="{% url 'main:home' %}" class="logo_heading">Tick</a>
                </div>
                <img class="dark mobile-dark" onclick="setTheme('dark')" style="width: 6%;" src="{% static 'images/toggle.svg' %}"
                    alt="dark mode icon">
                <img onclick="setTheme('light')" class="light mobile-light" style="width: 6%;" src="{% static 'images/toggle.svg' %}"
                    alt="light mode icon">
                    


                <div class="menu_hamburger">
                    <span></span>
                    <span></span>
                    <span></span>
                </div>

                <nav class="mobile_nav">

                    <ul>
                        <li><a href="index.html"><img class="nav-icon" src="{% static 'Images/mobile/home.svg' %}" alt="Home icon">
                                Home</a></li>
                        <li><a href="#"><img class="nav-icon" src="{% static 'Images/mobile/listing.svg' %}" alt="Listings icon">Listings</a></li>
                        <li><a href="#"><img class="nav-icon" src="{% static 'Images/mobile/podcast.svg' %}" alt="Podcasts icon">
                                Podcasts</a></li>
                        <li><a href="#"><img class="nav-icon" src="{% static 'Images/mobile/videos.svg' %}" alt="Videos icon"> Videos</a></li>
                        <li><a href="#"><img class="nav-icon" src="{% static 'Images/mobile/FAQ.svg' %}" alt="FAQ icon"> FAQ</a></li>
                        <li><a href="./t&c.html"><img class="nav-icon" src="{% static 'Images/mobile/terms.svg' %}" alt="Terms of use
                                    icon">
                                Terms of use</a></li>
                        <li><a href="./privacy.html"><img class="nav-icon" src="{% static 'Images/mobile/privacy.svg' %}" alt="Privacy
                                    policy icon">
                                Privacy Policy</a></li>
                        <li><a href="contact.html"><img class="nav-icon" src="{% static 'Images/mobile/contact-us.svg' %}" alt="Contact-us icon">
                                Contact us</a></li>
                        <li><a href="about.html"><img class="nav-icon" src="{% static 'Images/mobile/about-us.svg' %}" alt="About-us icon">
                                About us</a></li>
                        <li><a href="login.html"><img class="nav-icon" src="{% static 'Images/mobile/login.svg' %}" alt="Login icon">
                                Login</a></li>
                        <li><a href="signup.html"><img class="nav-icon" src="{% static 'Images/mobile/write.svg' %}" alt="Write-for-us
                                    icon">
                                Write for us</a></li>
                    </ul>
                </nav>
            </div>
        </header>
        <div class="container">
        
        
        <form  class="form-control" method="Post">
        <h1 align="center">Delete Post</h1>
        <h3>Are you sure you want to delete this post?</h3>
        {% csrf_token %}
        <button class="btn btn-primary">Delete Post</button>    
        </div>
    </body>
</html>












    
    

Tick/main/templates/detail.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link rel="shortcut icon" href="./Images/favicon.ico" type="image/x-icon" />
        <link
            href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;700&family=Jost:wght@500;700&family=Oxanium:wght@400;500;600;700&display=swap"
            rel="stylesheet"
            />
            <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
        <link rel="stylesheet" href="{% static 'css/style.css' %}" />
        <script src="{% static 'javascripts/script.js' %}" defer></script>
        <title>Tick-Blog</title>
    </head>
    <body>
        <header>
            <!-- desktop menu -->
            <div class="desktop_menu">
                <div class="desktop_menu-rside">
                    <div>
                        <a href="{% url 'main:home' %}" class="logo_heading">Tick</a>
                    </div>
                </div>
                <nav class="desktop_nav">
                    <img class="dark" onclick="setTheme('dark')" style="width: 5.3%;" src="{% static 'Images/toggle.svg' %}"
                        alt="dark mode icon">
                    <img onclick="setTheme('light')" class="light" style="width: 5.3%;" src="{% static 'Images/toggle.svg' %}"
                        alt="light mode icon">
        
                        {% if user.is_authenticated %}
                            
                        <ul>
                            <li>
                              <a href="#">welcome, {{user.username}}</a>
                            </li>
                            <li>
                                <a href="{% url 'main:create' %}">Add Post</a>
                              </li>
                              
                            <li>
                                <a href="{% url 'main:profile' %}">Add profile Picture </a>
                              </li>
                            <li><a href="{% url 'accounts:logout' %}">Logout</a></li>
                            </ul>
                            
                            {% else %}
                            
                            <li><a href="{% url 'accounts:login' %}" class="create_acct_btn">Login</a></li>
                            <li><a href="{% url 'accounts:signUp' %}" class="create_acct_btn">Create account</a></li> 
                            </ul>
                        {% endif %}

                </nav>
            </div>
            
            <!-- mobile menu -->
            <div class="mobile_menu">
                <div>
                    <a href="{% url 'main:home' %}" class="logo_heading">Tick</a>
                </div>
                <img class="dark mobile-dark" onclick="setTheme('dark')" style="width: 6%;" src="{% static 'images/toggle.svg' %}"
                    alt="dark mode icon">
                <img onclick="setTheme('light')" class="light mobile-light" style="width: 6%;" src="{% static 'images/toggle.svg' %}"
                    alt="light mode icon">
                    


                <div class="menu_hamburger">
                    <span></span>
                    <span></span>
                    <span></span>
                </div>

                <nav class="mobile_nav">

                    <ul>
                        <li><a href="index.html"><img class="nav-icon" src="{% static 'Images/mobile/home.svg' %}" alt="Home icon">
                                Home</a></li>
                        <li><a href="#"><img class="nav-icon" src="{% static 'Images/mobile/listing.svg' %}" alt="Listings icon">Listings</a></li>
                        <li><a href="#"><img class="nav-icon" src="{% static 'Images/mobile/podcast.svg' %}" alt="Podcasts icon">
                                Podcasts</a></li>
                        <li><a href="#"><img class="nav-icon" src="{% static 'Images/mobile/videos.svg' %}" alt="Videos icon"> Videos</a></li>
                        <li><a href="#"><img class="nav-icon" src="{% static 'Images/mobile/FAQ.svg' %}" alt="FAQ icon"> FAQ</a></li>
                        <li><a href="./t&c.html"><img class="nav-icon" src="{% static 'Images/mobile/terms.svg' %}" alt="Terms of use
                                    icon">
                                Terms of use</a></li>
                        <li><a href="./privacy.html"><img class="nav-icon" src="{% static 'Images/mobile/privacy.svg' %}" alt="Privacy
                                    policy icon">
                                Privacy Policy</a></li>
                        <li><a href="contact.html"><img class="nav-icon" src="{% static 'Images/mobile/contact-us.svg' %}" alt="Contact-us icon">
                                Contact us</a></li>
                        <li><a href="about.html"><img class="nav-icon" src="{% static 'Images/mobile/about-us.svg' %}" alt="About-us icon">
                                About us</a></li>
                        <li><a href="login.html"><img class="nav-icon" src="{% static 'Images/mobile/login.svg' %}" alt="Login icon">
                                Login</a></li>
                        <li><a href="signup.html"><img class="nav-icon" src="{% static 'Images/mobile/write.svg' %}" alt="Write-for-us
                                    icon">
                                Write for us</a></li>
                    </ul>
                </nav>
            </div>
        </header>
        <div>
        <h2> {{ object.Title }}</h2><br><hr>
                <img src="{{object.Images.url}}" alt="No Image"> <br/><br/>
                {{ object.Body|safe }}<br/><br/> 
       
       <h2>Comments.....</h2>

       {% if not object.comment.all %}

       No comment Yet...
       <a href="{% url 'main:add_comment' object.pk %}"><button>Add Comment</button></a>

       {% else %}

       {% for comment in object.comment.all %}

       {{comment.name}}-
       {{comment.date_added}}</br>

       {{comment.body}}</br></br>
       {% endfor %}
    
       <a href="{% url 'main:add_comment' object.pk %}"><button>Add Comment</button></a>
       {% endif %}
                
        </div>
        
        {% comment %} <footer class="footer">
            <p>
                Tick — A space where techies can interact with like
                    minds
                    and share ideas.
            </p>
                <p>
                    Built with HTML, Vanilla CSS and Javascript.
                </p>
                <p>Made by Team8 - Tick. JP Community &copy; 2022.</p>
        </footer> {% endcomment %}
             
    </body>
</html>            


   


        

        
        
   










    
    

Tick/main/templates/global.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link rel="shortcut icon" href="./Images/favicon.ico" type="image/x-icon" />
        <link
            href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;700&family=Jost:wght@500;700&family=Oxanium:wght@400;500;600;700&display=swap"
            rel="stylesheet"
            />
            <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
        <link rel="stylesheet" href="{% static 'css/style.css' %}" />
        <script src="{% static 'javascripts/script.js' %}" defer></script>
        <title>Tick-Blog</title>
    </head>
    <body>
        <header>
            <!-- desktop menu -->
            <div class="desktop_menu">
                <div class="desktop_menu-rside">
                    <div>
                        <a href="{% url 'main:home' %}" class="logo_heading">Tick</a>
                    </div>
                </div>
                <nav class="desktop_nav">
                    <img class="dark" onclick="setTheme('dark')" style="width: 5.3%;" src="{% static 'Images/toggle.svg' %}"
                        alt="dark mode icon">
                    <img onclick="setTheme('light')" class="light" style="width: 5.3%;" src="{% static 'Images/toggle.svg' %}"
                        alt="light mode icon">
        
                        {% if user.is_authenticated %}
                            
                        <ul>
                            <li>
                              <a href="#">welcome, {{user.username}}</a>
                            </li>
                            <li>
                                <a href="{% url 'main:create' %}">Add Post</a>
                              </li>
                              
                            <li>
                                <a href="{% url 'main:profile' %}">Add profile Picture </a>
                              </li>
                            <li><a href="{% url 'accounts:logout' %}">Logout</a></li>
                            </ul>
                            
                            {% else %}
                            
                            <li><a href="{% url 'accounts:login' %}" class="create_acct_btn">Login</a></li>
                            <li><a href="{% url 'accounts:signUp' %}" class="create_acct_btn">Create account</a></li> 
                            </ul>
                        {% endif %}

                </nav>
            </div>
            <!-- mobile menu -->
            <div class="mobile_menu">
                <div>
                    <a href="{% url 'main:home' %}" class="logo_heading">Tick</a>
                </div>
                <img class="dark mobile-dark" onclick="setTheme('dark')" style="width: 6%;" src="{% static 'images/toggle.svg' %}"
                    alt="dark mode icon">
                <img onclick="setTheme('light')" class="light mobile-light" style="width: 6%;" src="{% static 'images/toggle.svg' %}"
                    alt="light mode icon">
                    


                <div class="menu_hamburger">
                    <span></span>
                    <span></span>
                    <span></span>
                </div>

                <nav class="mobile_nav">

                    <ul>
                        <li><a href="index.html"><img class="nav-icon" src="{% static 'Images/mobile/home.svg' %}" alt="Home icon">
                                Home</a></li>
                        <li><a href="#"><img class="nav-icon" src="{% static 'Images/mobile/listing.svg' %}" alt="Listings icon">Listings</a></li>
                        <li><a href="#"><img class="nav-icon" src="{% static 'Images/mobile/podcast.svg' %}" alt="Podcasts icon">
                                Podcasts</a></li>
                        <li><a href="#"><img class="nav-icon" src="{% static 'Images/mobile/videos.svg' %}" alt="Videos icon"> Videos</a></li>
                        <li><a href="#"><img class="nav-icon" src="{% static 'Images/mobile/FAQ.svg' %}" alt="FAQ icon"> FAQ</a></li>
                        <li><a href="./t&c.html"><img class="nav-icon" src="{% static 'Images/mobile/terms.svg' %}" alt="Terms of use
                                    icon">
                                Terms of use</a></li>
                        <li><a href="./privacy.html"><img class="nav-icon" src="{% static 'Images/mobile/privacy.svg' %}" alt="Privacy
                                    policy icon">
                                Privacy Policy</a></li>
                        <li><a href="contact.html"><img class="nav-icon" src="{% static 'Images/mobile/contact-us.svg' %}" alt="Contact-us icon">
                                Contact us</a></li>
                        <li><a href="about.html"><img class="nav-icon" src="{% static 'Images/mobile/about-us.svg' %}" alt="About-us icon">
                                About us</a></li>
                        <li><a href="login.html"><img class="nav-icon" src="{% static 'Images/mobile/login.svg' %}" alt="Login icon">
                                Login</a></li>
                        <li><a href="signup.html"><img class="nav-icon" src="{% static 'Images/mobile/write.svg' %}" alt="Write-for-us
                                    icon">
                                Write for us</a></li>
                    </ul>
                </nav>
            </div>
        </header>
            <div>
                <div class="container">
                    {% block content %}
        
                    
                    {% endblock %}

                </div>
            </div><br/><br/><br/>
        
        <footer class="footer">
            <p>
                Tick — A space where techies can interact with like
                    minds
                    and share ideas.
            </p>
                <p>
                    Built with HTML, Vanilla CSS and Javascript.
                </p>
                <p>Made by Team8 - Tick. JP Community &copy; 2022.</p>
        </footer>
             
    </body>
</html>            

Tick/main/templates/profile.html
{% extends 'global.html' %}

{% block content %}
        <form  class="form-control" method="Post">
            <h1 align="center">Upload Profile Picture</h1>
            {% csrf_token %}
            {{form.as_p}}<br/><br/><br/><br/><br/><br/>
            <button class="btn btn-primary">Post</button>  
            <script> 
                var name="{{user.username}}";
                document.getElementById("author").placeholder
                    =name;
            </script>  
        
{% endblock %}